# Server Configuration
server.port=8081
spring.application.name=user-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecom_users?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=My$ql100jk
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Developer Tools
spring.devtools.restart.enabled=true