spring.application.name=user-service
server.port=9020

# Service registry
eureka.client.service-url.defaultZone=http://localhost:8090/eureka/

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://mysql-9829c8e-aerocommerce.f.aivencloud.com:18823/ecom_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_H0jstUobK5cTgS73bn-
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect